# Generated by Django 3.2.9 on 2021-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.TextField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('playlist_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.TextField(primary_key=True, serialize=False)),
                ('artist_name', models.TextField()),
                ('song_name', models.TextField()),
                ('song_link', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
