# Generated by Django 3.2.9 on 2021-12-03 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('song_artists', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('song_link', models.CharField(max_length=100)),
                ('likes', models.ManyToManyField(blank=True, related_name='songLikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
                ('followers', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('playlist_link', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='playlistLikes', to=settings.AUTH_USER_MODEL)),
                ('shares', models.ManyToManyField(blank=True, related_name='playlistShares', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='musicdb.Song')),
            ],
        ),
    ]
