# Generated by Django 3.2.9 on 2021-11-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('musicdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='followers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner_name',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='users.userentity'),
            preserve_default=False,
        ),
    ]
