# Generated by Django 3.2.9 on 2021-12-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(max_length=1000),
        ),
    ]
