# Generated by Django 3.2.9 on 2021-11-27 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0003_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
