# Generated by Django 3.2.9 on 2021-12-01 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0005_auto_20211130_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
