# Generated by Django 3.2.9 on 2021-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0007_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
