# Generated by Django 3.2.9 on 2021-12-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0008_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='owner_name',
            new_name='creator',
        ),
    ]
