# Generated by Django 3.2.9 on 2021-12-02 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicdb', '0010_alter_playlist_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(related_name='playlistLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='shares',
            field=models.ManyToManyField(related_name='playlistShares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='songLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
