# Generated by Django 3.2.9 on 2021-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0012_auto_20211202_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_link',
            field=models.TextField(default='https://spotify.com'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.TextField(default='My Playlist'),
        ),
    ]
