# Generated by Django 3.2.9 on 2021-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0014_auto_20211202_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_link',
            field=models.CharField(default='https://spotify.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='My Playlist', max_length=100),
        ),
    ]
