# Generated by Django 3.2.9 on 2021-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0015_auto_20211202_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(max_length=100),
        ),
    ]
