# Generated by Django 3.2.9 on 2021-12-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0016_auto_20211202_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_artists',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=100),
        ),
    ]
