# Generated by Django 3.2.9 on 2021-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('playlist_count', models.IntegerField()),
                ('country', models.TextField()),
                ('display_name', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
