# Generated by Django 3.2.9 on 2021-11-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0002_auto_20211114_2227'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicdb.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentity',
            name='playlists',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='musicdb.playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentity',
            name='shares',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musicdb.playlist'),
            preserve_default=False,
        ),
    ]
