# Generated by Django 3.2.9 on 2021-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='PASSWORD_FIELD',
            field=models.TextField(default='default_password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentity',
            name='USERNAME_FIELD',
            field=models.TextField(default='default_username'),
            preserve_default=False,
        ),
    ]
