# Generated by Django 3.2.9 on 2021-12-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0009_rename_owner_name_playlist_creator'),
        ('users', '0004_auto_20211127_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userentity',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='userentity',
            name='shares',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='profile_pics')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('playlist_count', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicdb.song')),
                ('playlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.playlist')),
                ('shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musicdb.playlist')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following_username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='username',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('username', 'following_username')},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_id',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user_id',
        ),
    ]
