# Generated by Django 3.2.9 on 2021-12-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0010_alter_playlist_creator'),
        ('users', '0005_auto_20211201_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEntity',
        ),
    ]
