# Generated by Django 3.2.9 on 2021-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shares',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist_count',
            field=models.IntegerField(default=0),
        ),
    ]
