# Generated by Django 3.2.9 on 2021-12-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211202_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars'),
        ),
    ]
