# Generated by Django 3.2.9 on 2021-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
